### ISSUE TITLE
Button Toggle Group

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-themes#1]
#### Describe the bug
Button Toggle group, the divider between each button goes missing

#### What is the expected behavior?
It doesn't 

#### What are the steps to reproduce?
Open showcase theme demo.

**Comment by joebochill** [comment]
Let's look at this again and if we can't fix it, then let's close the issue and mark it as wont-fix

**Comment by ektasawant** [comment]
Border is disappearing because of line no: https://github.com/brightlayer-ui/angular-themes/blob/dev/mixins/button.scss#L114. 
<img width="325" alt="Screenshot 2022-01-06 at 3 38 55 PM" src="https://user-images.githubusercontent.com/10433274/148367362-6f552ca6-ed57-4e5a-a593-4bab5873889d.png">

Any page where we have applied this line https://github.com/brightlayer-ui/angular-themes/blob/dev/mixins/button.scss#L114 ?

**Comment by emclaug2** [comment]
Fixed in #58
